import services from './services'

export default {
  [services.acm]: 'acms',
  [services.alb]: 'albs',
  [services.apiGatewayDomainName]: 'apiGatewayDomainNames',
  [services.apiGatewayHttpApi]: 'apiGatewayHttpApis',
  [services.apiGatewayResource]: 'apiGatewayResources',
  [services.apiGatewayRestApi]: 'apiGatewayRestApis',
  [services.apiGatewayStage]: 'apiGatewayStages',
  [services.asg]: 'asgs',
  [services.athenaDataCatalog]: 'athenaDataCatalogs',
  [services.cloud9]: 'cloud9Environments',
  [services.cloudFormationStack]: 'cloudFormationStacks',
  [services.cloudFormationStackSet]: 'cloudFormationStackSets',
  [services.cloudfront]: 'cloudfrontDistributions',
  [services.cloudwatchLog]: 'cloudwatchLogs',
  [services.codebuild]: 'codebuilds',
  [services.configurationRecorder]: 'configurationRecorders',
  [services.dmsReplicationInstance]: 'dmsReplicationInstances',
  [services.ebsSnapshot]: 'ebsSnapshots',
  [services.ec2Instance]: 'ec2Instances',
  [services.ecsCluster]: 'ecsClusters',
  [services.ecsContainer]: 'ecsContainers',
  [services.ecsService]: 'ecsServices',
  [services.ecsTask]: 'ecsTasks',
  [services.ecsTaskDefinition]: 'ecsTaskDefinitions',
  [services.ecsTaskSet]: 'ecsTaskSets',
  [services.eksCluster]: 'eksClusters',
  [services.elastiCacheCluster]: 'elastiCacheClusters',
  [services.elastiCacheReplicationGroup]: 'elastiCacheReplicationGroups',
  [services.elasticBeanstalkApp]: 'elasticBeanstalkApps',
  [services.elasticBeanstalkEnv]: 'elasticBeanstalkEnvs',
  [services.elasticSearchDomain]: 'elasticSearchDomains'
}
